#!/usr/bin/env php
<?php

include 'vendor/autoload.php';

use Myth\CLI as CLI;

CLI::_init();

$status = 0;

/**
 * Relative location to the application's
 * index.php from this file.
 */
$apppath = 'index.php';

/**
 * Refuse to run oil when called from php-cgi !
 */
if (substr(php_sapi_name(), 0, 3) == 'cgi')
{
    die("This is not supported when running php-cgi. Sprint needs php-cli to function!\n\n");
}

/**
 * Set error reporting and display errors settings.  You will want to change these when in production.
 */
error_reporting(-1);
ini_set('display_errors', 1);



//--------------------------------------------------------------------
// Do the Things
//--------------------------------------------------------------------

// Default to a simple passthru of the basic command, less arguments.
$command = CLI::cli_string();

// If -h or --help or -help are present, then we'll return the command's
// Long description, if available.
if (CLI::option('h') || CLI::option('hello')) {
    $command = CLI::segment(1) . ' longDescribeMethod ' . CLI::segment(2);
}

// Standard Method call to CodeIgniter
passthru("php {$apppath} {$command}", $status);

exit($status);

